package br.edu.ifsp.dmo5.alugel.carros.Constant;

public class Constant {
    public final static String DATABASE_USER = "User";
    public final static String DATABASE_CARRO = "Carro";
    public final static String DATABASE_ID = "Id";
    public final static String DATABASE_NOME = "Nome";
    public final static String DATABASE_CPF = "Cpf";
    public final static String DATABASE_CNH = "Cnh";
    public final static String PHOTO = "Foto";
    public final static String ACTIVE = "IsActive";
    public final static String DATABASE_CNH_VALIDADE = "CnhValidade";
    public final static String DATABASE_LOGADOURO = "Logadouro";
    public final static String DATABASE_NUMERO = "Numero";
    public final static String DATABASE_BAIRRO = "Bairro";
    public final static String DATABASE_CIDADE = "Cidade";
    public final static String DATABASE_ALUGADO = "Alugado";
    public final static String DATABASE_ESTADO = "Estado";
    public final static String DATABASE_CEP = "Cep";
    public final static String DATABASE_TELEFONE = "Telefone";
    public final static String DATABASE_EMAIL = "Email";
    public final static String DATABASE_DATA_NASCIMENTO = "DataDeNascimento";
    public final static String DATABASE_SENHA = "Senha";
    public final static String CARRO_MODEL = "CarroModel";
    public final static String ID_DONO_CARRO = "DonoDoCaroId";
    public final static String MARCA = "Marca";
    public final static String MMODELO = "Modelo";
    public final static String COR = "Cor";
    public final static String PLACA = "Placa";
    public final static String TIPO_COMBUSTIVEL = "TipoCombustivel";
    public final static String AR = "Ar";
    public final static String PORTAS = "Porta";
    public final static String ELETRICO = "Eletrico";
    public final static String RADIO = "Radio_Gps";
    public final static String QUILOMETRAGEM = "Quilometragem";
    public final static String CRLVE = "Crlve";
    public final static String CPF_PROPRIETARIO = "CpfProprietario";
    public final static String PRECO_POR_DIA = "PrecoPorDia";
    public final static String MODELO_CARRO = "Modelo do carro";
    public final static String DONO_CARRO = "Dono do carro";
    public final static String DATABASE_CARRO_XUSER = "CarroXUser";
    public final static String CARRO_ID = "CarroId";
    public final static String USER_ID = "UserId";
    public final static String SUCESSO_ALUGUEL = "Aluguel realizado com sucesso";
    public final static String ERRO_ALUGUEL = "Selecione uma data para alugar";
    public static final String CNH_CATEGORIA = "CnhCategoria";
    public static final String DATABASE_DATA = "Data";
    public static final String DATABASE_DATA_FIM = "DataFim";
    public static final String DATABASE_CARRO_ENTREGUE= "CarroEntregue";
    public static final String MENSAGEM_CNH_ERROR = "Para acessar os carros apra alugar por favor coloque os dados da CNH";
    public static final String USER_PREFERENCES = "UserManterConectado";

}
